agent:
  name: 'devops-tpl-agent'
  version: '0.0.1'
  pollInterval: 2
  reportInterval: 10
  server_url: "http://127.0.0.1:8080/"

server:
  name: 'devops-tpl-server'
  version: '0.0.1'
  port: '8080'

logger:
  log_level: 'debug'
